### PR TITLE
Proposed to add Fabien Potencier (Symfony)

### PR DESCRIPTION
**Pull request by javiereguiluz**
Symfony is one of the most popular open-source projects, with [more than 500 million downloads](http://symfony.com/blog/symfony-reaches-500-million-downloads) in just 5 years.

### CODE REVIEW

**Comment by garak** [comment]
agree

**Comment by javiereguiluz** [comment]
I don't know what's going here. GitHub says that I closed this PR and that it was merged. But I didn't close this and this wasn't merged. And GitHub doesn't allow me to reopen it.

**Comment by tgabi333** [comment]
+1

**Comment by mrcmorales** [comment]
+1

**Comment by stof** [comment]
@javiereguiluz it also says that no file was modified in this PR (which is why it go closed) ? Did you try to amend the PR and pushed the wrong commit by mistake ?

**Comment by javiereguiluz** [comment]
@rekihattori thanks for accepting and merging this proposal!

**Comment by rekihattori** [comment]
@javiereguiluz thank you for contributing and recommending the symfony creator

**Pull request merged**
